name: Daily YTAutomator

on:
  schedule:
    # Runs at multiple times (converted to UTC for America/New_York timezone):
    # 9:00  local -> 13:00 UTC, 12:00 -> 16:00, 14:00 -> 18:00, 19:00 -> 23:00, 22:00 -> 02:00
    - cron: '0 13 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
    - cron: '0 23 * * *'
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Restore credentials (from base64 secrets)
        env:
          CLIENT_SECRET_B64: ${{ secrets.CLIENT_SECRET_JSON_B64 }}
          TOKEN_JSON_B64: ${{ secrets.TOKEN_JSON_B64 }}
        run: |
          if [ -n "$CLIENT_SECRET_B64" ]; then
            echo "$CLIENT_SECRET_B64" | base64 --decode > client_secret.json
            echo "Wrote client_secret.json"
          else
            echo "CLIENT_SECRET_JSON_B64 not set, skipping client_secret.json"
          fi
          if [ -n "$TOKEN_JSON_B64" ]; then
            echo "$TOKEN_JSON_B64" | base64 --decode > token.json
            echo "Wrote token.json"
          else
            echo "TOKEN_JSON_B64 not set, skipping token.json"
          fi

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          # Add any API keys your project needs as repository secrets and map them here
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # If your code expects different env names, add them accordingly
        run: |
          python main.py --run-once

      - name: Upload generated videos and temp files (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yt-outputs
          path: |
            output/**/short*.mp4
            output/**/tmp_v/**

      - name: Notify on failure to Slack (optional)
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          if [ -z "$SLACK_WEBHOOK" ]; then
            echo "SLACK_WEBHOOK not set, skipping notification"
            exit 0
          fi
          payload=$(jq -n --arg text "YTAutomator workflow failed. Check artifacts for details." '{text: $text}')
          curl -s -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK"